#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const SCHEMAS_DIR = path.join(__dirname, '../prisma/schemas');
const OUTPUT_FILE = path.join(__dirname, '../prisma/schema.prisma');
const BASE_SCHEMA = `// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

// ============================================
// Generator & Datasource
// ============================================
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

// ============================================
// Domain Schemas
// ============================================
// This file is auto-generated by merge-schemas.js
// DO NOT EDIT THIS FILE DIRECTLY
// Edit the files in prisma/schemas/ instead and run: npm run schema:merge
// ============================================

`;

function mergeSchemas() {
  try {
    // schemas 디렉토리 확인
    if (!fs.existsSync(SCHEMAS_DIR)) {
      console.error(`Error: ${SCHEMAS_DIR} directory does not exist`);
      process.exit(1);
    }

    // .prisma 파일 찾기
    const schemaFiles = fs
      .readdirSync(SCHEMAS_DIR)
      .filter(file => file.endsWith('.prisma'))
      .sort(); // 알파벳 순서로 정렬

    if (schemaFiles.length === 0) {
      console.error(`Error: No .prisma files found in ${SCHEMAS_DIR}`);
      process.exit(1);
    }

    console.log(`Found ${schemaFiles.length} schema file(s):`);
    schemaFiles.forEach(file => console.log(`  - ${file}`));

    // 각 파일 내용 읽기 및 병합
    let mergedContent = BASE_SCHEMA;
    
    schemaFiles.forEach((file, index) => {
      const filePath = path.join(SCHEMAS_DIR, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      
      mergedContent += `\n// ============================================\n`;
      mergedContent += `// From: ${file}\n`;
      mergedContent += `// ============================================\n\n`;
      mergedContent += content;
      
      if (index < schemaFiles.length - 1) {
        mergedContent += '\n';
      }
    });

    // 출력 파일에 작성
    fs.writeFileSync(OUTPUT_FILE, mergedContent, 'utf-8');
    
    console.log(`\n✓ Successfully merged schemas into ${OUTPUT_FILE}`);
    console.log(`  Total lines: ${mergedContent.split('\n').length}`);
    
  } catch (error) {
    console.error('Error merging schemas:', error.message);
    process.exit(1);
  }
}

mergeSchemas();
